openapi: 3.0.1
info:
  title: ViaCEP API
  description: API pública para consulta de endereços brasileiros por CEP
  version: 1.0.0
servers:
  - url: https://viacep.com.br/ws
paths:
  /{cep}/json/:
    get:
      summary: Retorna informações de endereço para o CEP informado
      parameters:
        - name: cep
          in: path
          required: true
          schema:
            type: string
            example: "01001000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cep:
                    type: string
                  logradouro:
                    type: string
                  complemento:
                    type: string
                  bairro:
                    type: string
                  localidade:
                    type: string
                  uf:
                    type: string
