openapi: 3.0.0
info:
  title: ViaCEP API
  description: API pública para consulta de endereços por CEP no Brasil
  version: "1.0.0"
servers:
  - url: https://viacep.com.br/ws
paths:
  /{cep}/json:
    get:
      summary: Consulta dados de endereço por CEP
      parameters:
        - name: cep
          in: path
          required: true
          schema:
            type: string
          example: "01001-000"
      responses:
        '200':
          description: Endereço correspondente ao CEP consultado
          content:
            application/json:
              schema:
                type: object
                properties:
                  cep:
                    type: string
                  logradouro:
                    type: string
                  complemento:
                    type: string
                  unidade:
                    type: string
                  bairro:
                    type: string
                  localidade:
                    type: string
                  uf:
                    type: string
                  estado:
                    type: string
                  regiao:
                    type: string
                  ibge:
                    type: string
                  gia:
                    type: string
                  ddd:
                    type: string
                  siafi:
                    type: string
